// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import Header from "./components/Header";
// import "./globals.css";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//     >
//       <body className="min-h-full flex flex-col"> 
//         {/* <Header /> */}
       
//       {children}</body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Lexend, Lora } from "next/font/google"; 
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer"

// 1. Lexend - subsets-ийг 'as any' гэж хүчээр зааж өгнө
const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"] as any, // Эхлээд latin гээд, доор нь preload-оор cyrillic-ийг дуудна
  weight: ["300", "400", "500", "700"],
  display: "swap", // Фонт ачаалтал хүлээхгүй шууд харуулна
});

// 2. Lora - Гарчигт зориулсан
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"] as any,
  style: ["italic", "normal"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Зөв Бичгийн Баатар",
  description: "Монгол хэлний цээж бичгийн платформ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="mn">
      {/* Head дотор Google Fonts-оос Cyrillic-ийг заавал ачааллах холбоосыг нэмж өгч болно (optional) */}
      <head />
      <body className={`${lexend.variable} ${lora.variable} font-sans antialiased min-h-screen flex flex-col`}> 
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}